### ISSUE TITLE
`client` requires ToJSVal and FromJSVal instances instead of using ToJSON and FromJSON

### ISSUE THREAD

**Issue by ublubu** [plow-technologies/ghcjs-servant-client#5]
Clients shouldn't convert JSON to JSVal and then convert JSVal to haskell datatypes. The conversion should be directly between haskell types and JSON.

If I'm mistaken in this, how can I automatically generate matching (To|From)JSVal instances from their (To|From)JSON counterparts?

**Comment by mchaver** [comment]
@ublubu 

I believe this is done performance reasons. It's runs a lot faster if you work with JSVals than swapping back and forth between JSVal and JSON (when the client receives it it is going to be a JSVal already).

We have a package that helps do this manually:
https://github.com/plow-technologies/ghcjs-jsval-combinators

Here is a simple example using ghcjs-jsval-combinators (I should add that to the README and some tests as well):
https://github.com/plow-technologies/ghcjs-servant-client/blob/master/tests/Api.hs#L80

For toJSVal you can take advantage of the toJSON instances with `toJSVal_aeson`

``` Haskell
instance ToJSVal ByteString where
  toJSVal = toJSVal_aeson
```

The same doesn't exist for fromJSVal, but you can do something like this with `decode . encode`:

``` Haskell
instance FromJSVal ByteString where
  fromJSVal v = do
    mv <- fromJSVal v :: IO (Maybe Text)
    case mv of
      Nothing -> return Nothing
      Just b -> return $ decode . encode $ b
```

Here is another useful one

``` Haskell
instance ToJSVal UTCTime where
  toJSVal = toJSVal_aeson

instance FromJSVal UTCTime where
  fromJSVal v = do
    mTime <- fromJSVal v :: IO (Maybe Text)
    case mTime of
      Nothing -> return Nothing
      Just time -> return $ decode . encode $ time
```
